version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/
    schedule:
      interval: "weekly"
