name: Build and Test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v5
      
      - name: Build Solution
        run: dotnet build -c Release
      
      - name: Run Unit Tests
        run: dotnet test -c Release --no-build