name: Publish to Nuget.org

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true
        type: string

env:
  PROJECT_NAME: 'Readability.NET'
  NUPKG_NAME: 'readability-net.nupkg'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v5

      - name: Print .NET Version
        run: dotnet --version
      
      - name: Build Solution
        run: dotnet build -c Release
      
      - name: Run Unit Tests
        run: dotnet test -c Release --no-build

      - name: Pack NuGet package
        run: dotnet pack ${{ env.PROJECT_NAME }} --configuration Release --no-build -p:PackageVersion=${{ inputs.package_version }} --output ./artifacts

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USERNAME }}
        
      - name: Publish to Nuget
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json